### ISSUE TITLE
Kintetsu bus

### ISSUE THREAD

**Issue by R-James** [poohsan1349/odentools-bus#11]
It allows you to display arrival time of Shinobugaoka Station for the indication of the Kintetsu bus.

**Comment by poohsan1349** [comment]
私のアプリというより，データを引っ張てくる元のサーバー側が登録していない問題なので，私自身どうしようもないです．サーバー側の人には話したので今後追加されるかもしれません．

**Comment by poohsan1349** [comment]
@R-James Hi, Ryota. We told Yoshida about your request. Thankyou.
https://github.com/odentools/diagram/issues/113
