### ISSUE TITLE
通知タイミングスピナーの展開時サイズを大きくする

### ISSUE THREAD

**Issue by mugifly** [poohsan1349/odentools-bus#12]
通知タイミングのスピナーについて，展開したときのサイズが小さすぎる気がします．
もう少し大きくしたほうがいいかもしれません．

**Comment by poohsan1349** [comment]
![spinner_change](https://cloud.githubusercontent.com/assets/14799658/16909554/8677113a-4d0e-11e6-80e3-79a2ac5cf61a.png)
これでよろしいでしょうか？

**Comment by mugifly** [comment]
デザイン上，＠〜〜の左右にもパディングがあると良い気がしますね．

**Comment by poohsan1349** [comment]
![spinner_change](https://cloud.githubusercontent.com/assets/14799658/16915296/ca0f00d8-4d31-11e6-82b7-4d3db5b90a4c.png)
これでどうですか？

**Comment by mugifly** [comment]
良いですね！ありがとうございます．嬉しいです．
